#!/bin/bash
# chkconfig:         2345 90 10
# description:       Service runner for ETCD
### BEGIN INIT INFO
# Provides:          etcd
# Required-Start:    $syslog $network
# Required-Stop:     $syslog $network
# Should-Start:      etcd
# Should-Stop:       etcd
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the etcd server
# Description:       Manages the etcd server
### END INIT INFO

PATH="/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin"

if [ -e /etc/etcd/config ] ; then
   . /etc/etcd/config
fi

start(){
    if status; then
        echo "etcd is already running"
        return 1
    fi
    /usr/local/bin/etcd \
		$ETCD_CONFIG_NAME \
		$ETCD_DATA_DIR \
		$ETCD_CLUSTER_ARGS \
		$ETCD_PEER_ARGS \
		$ETCD_CLIENT_ARGS \
	    $ETCD_OTHER_ARGS &
}

stop() {
    killall etcd
}

restart() {
    stop; start
}

status() {
    pgrep etcd
}

case "$1" in
    start) start;;
    stop) stop;;
    status) status;;
    restart) restart;;
    *)
        echo "Usage: $0 {start|stop|status|restart}"
        exit 1
        ;;
esac
